import{H as e,loadAsAdopted as t,ref as n,removeAdopted as o}from"../fest/dom.js";import{createViewState as i}from"./types.js";var a=class{id="editor";name="Editor";icon="pencil";options;shellContext;element=null;contentRef=n("");stateManager=i("rs-editor-state");textarea=null;_sheet=null;lifecycle={onMount:()=>this.onMount(),onUnmount:()=>this.saveState(),onShow:()=>{this._sheet??=t('@layer view.editor {\n  :is(html, body):has([data-view=editor]) {\n    --view-layout:"flex";\n    --view-content-max-width:none;\n  }\n  .view-editor {\n    background-color: var(--view-bg,var(--color-surface,#ffffff));\n    block-size: 100%;\n    color: var(--view-fg,var(--color-on-surface,#1a1a1a));\n    display: flex;\n    flex-direction: column;\n  }\n  .view-editor__toolbar {\n    align-items: center;\n    background-color: var(--view-toolbar-bg,rgba(0,0,0,.02));\n    border-block-end: 1px solid var(--view-border,rgba(0,0,0,.08));\n    display: flex;\n    flex-shrink: 0;\n    gap: .5rem;\n    justify-content: space-between;\n    padding: .5rem 1rem;\n  }\n  .view-editor__toolbar-left,\n  .view-editor__toolbar-right {\n    align-items: center;\n    display: flex;\n    gap: .25rem;\n  }\n  .view-editor__btn {\n    align-items: center;\n    background: transparent;\n    border: none;\n    border-radius: 6px;\n    color: var(--view-fg);\n    cursor: pointer;\n    display: flex;\n    font-size: .8125rem;\n    font-weight: 500;\n    gap: .5rem;\n    padding: .5rem .75rem;\n    transition: background-color .15s ease;\n  }\n  .view-editor__btn ui-icon {\n    font-size: 1rem;\n    opacity: .7;\n  }\n  @media (max-width: 640px) {\n    .view-editor__btn span {\n      display: none;\n    }\n  }\n  .view-editor__btn:hover {\n    background-color: rgba(0, 0, 0, .06);\n  }\n  .view-editor__content {\n    display: flex;\n    flex: 1;\n    overflow: hidden;\n  }\n  .view-editor__textarea {\n    background-color: var(--view-editor-bg,#fafafa);\n    border: none;\n    color: var(--view-fg);\n    flex: 1;\n    font-family:\n      SF Mono,\n      Fira Code,\n      JetBrains Mono,\n      Consolas,\n      monospace;\n    font-size: .9375rem;\n    line-height: 1.6;\n    padding: 1.5rem 2rem;\n    resize: none;\n  }\n  .view-editor__textarea:focus {\n    outline: none;\n  }\n  .view-editor__textarea::placeholder {\n    color: var(--view-fg);\n    opacity: .4;\n  }\n  @media print {\n    .view-editor__toolbar {\n      display: none;\n    }\n    .view-editor__textarea {\n      padding: 0;\n    }\n  }\n}')},onHide:()=>{try{this._sheet&&o(this._sheet)}catch{}this._sheet=null,this.saveState()}};constructor(e={}){this.options=e,this.shellContext=e.shellContext;const t=this.stateManager.load();this.contentRef.value=e.initialContent||t?.content||"# New Document\n\nStart writing here..."}render(t){return t&&(this.options={...this.options,...t},this.shellContext=t.shellContext||this.shellContext),this.element=e`
            <div class="view-editor">
                <div class="view-editor__toolbar">
                    <div class="view-editor__toolbar-left">
                        <button class="view-editor__btn" data-action="open" type="button" title="Open file">
                            <ui-icon icon="folder-open" icon-style="duotone"></ui-icon>
                            <span>Open</span>
                        </button>
                        <button class="view-editor__btn" data-action="save" type="button" title="Save file">
                            <ui-icon icon="floppy-disk" icon-style="duotone"></ui-icon>
                            <span>Save</span>
                        </button>
                    </div>
                    <div class="view-editor__toolbar-right">
                        <button class="view-editor__btn" data-action="preview" type="button" title="Preview">
                            <ui-icon icon="eye" icon-style="duotone"></ui-icon>
                            <span>Preview</span>
                        </button>
                        <button class="view-editor__btn" data-action="copy" type="button" title="Copy all">
                            <ui-icon icon="copy" icon-style="duotone"></ui-icon>
                            <span>Copy</span>
                        </button>
                    </div>
                </div>
                <div class="view-editor__content">
                    <textarea
                        class="view-editor__textarea"
                        placeholder="Start writing markdown..."
                        data-editor-input
                    >${this.contentRef.value}</textarea>
                </div>
            </div>
        `,this.textarea=this.element.querySelector("[data-editor-input]"),this.setupEventHandlers(),this.element}getToolbar(){return null}setContent(e){this.contentRef.value=e,this.textarea&&(this.textarea.value=e)}getContent(){return this.contentRef.value}setupEventHandlers(){this.element&&(this.textarea?.addEventListener("input",()=>{this.contentRef.value=this.textarea?.value||"",this.options.onContentChange?.(this.contentRef.value)}),this.element.addEventListener("click",async e=>{const t=e.target.closest("[data-action]");if(!t)return;switch(t.dataset.action){case"open":this.handleOpen();break;case"save":this.handleSave();break;case"preview":this.handlePreview();break;case"copy":await this.handleCopy()}}))}handleOpen(){const e=document.createElement("input");e.type="file",e.accept=".md,.markdown,.txt,text/markdown,text/plain",e.onchange=async()=>{const t=e.files?.[0];if(t)try{const e=await t.text();this.setContent(e),this.options.filename=t.name,this.showMessage(`Opened ${t.name}`)}catch{this.showMessage("Failed to open file")}},e.click()}handleSave(){const e=this.contentRef.value,t=this.options.filename||"document.md",n=new Blob([e],{type:"text/markdown;charset=utf-8"}),o=URL.createObjectURL(n),i=document.createElement("a");i.href=o,i.download=t,i.click(),setTimeout(()=>URL.revokeObjectURL(o),250),this.options.onSave?.(e),this.showMessage(`Saved ${t}`)}handlePreview(){this.shellContext?.navigate("viewer")}async handleCopy(){try{const e=await writeClipboardText(this.contentRef.value);if(!e.ok)throw new Error(e.error||"Clipboard write failed");this.showMessage("Copied to clipboard")}catch{this.showMessage("Failed to copy")}}saveState(){this.stateManager.save({content:this.contentRef.value,filename:this.options.filename})}onMount(){console.log("[Editor] Mounted")}showMessage(e){this.shellContext?.showMessage(e)}async invokeChannelApi(e,t){const n=null==t||"object"!=typeof t||Array.isArray(t)?{}:t,o="string"==typeof n.text?n.text:"string"==typeof n.content?n.content:"string"==typeof t?t:"";return e===EditorChannelAction.SetContent||e===EditorChannelAction.ContentLoad||e===EditorChannelAction.ContentEdit?(o&&this.setContent(o),!0):(await this.handleMessage({type:e,data:{text:o,content:o}}),!0)}canHandleMessage(e){return["content-edit","content-load"].includes(e)}async handleMessage(e){const t=e;(t.data?.text||t.data?.content)&&this.setContent(t.data.text||t.data.content||"")}};function s(e){return new a(e)}var r=s;export{a as EditorView,r as createEditorView,s as createView,s as default};